# Generated by Django 2.2.6 on 2021-05-30 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_auto_20210419_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='description',
            field=models.TextField(help_text='Опиши тематику группы', verbose_name='Описание группы'),
        ),
    ]
