# Generated by Django 2.2.6 on 2021-06-02 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_auto_20210530_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, help_text='Можно вставить картинку', null=True, upload_to='posts/', verbose_name='Картинка'),
        ),
    ]
