# Generated by Django 2.2.6 on 2021-06-04 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
    ]
