# Generated by Django 2.2.6 on 2021-06-08 08:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0013_post_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='Пиши текст комментария здесь', max_length=1000, verbose_name='Комментарий к посту')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Отображается дата публикации комментария', verbose_name='Дата публикации')),
                ('author', models.ForeignKey(help_text='Указывается автор комментария', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='Автор комментария')),
                ('post', models.ForeignKey(blank=True, help_text='Добавь комментарий к посту', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comments', to='posts.Post', verbose_name='Комментарий к посту')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
